In [41]:
from graph_generator import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [73]:
date, ope, hig, low, close, start, end=triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)


In [96]:
low

0      30.477690
1      33.183766
2      37.517098
3      37.626544
4      38.052748
         ...    
493    30.203382
494    30.399794
495    37.245274
496    31.376286
497    31.754234
Length: 498, dtype: float64

In [98]:
ope=np.array(low)
hig=np.array(hig)

np.column_stack((ope, hig))

array([[ 30.47768978,  34.52701643],
       [ 33.18376623,  38.74723115],
       [ 37.5170981 ,  37.91364962],
       [ 37.62654357,  39.09129713],
       [ 38.05274786,  38.91448931],
       [ 35.65880228,  39.11408373],
       [ 35.09742452,  36.58682081],
       [ 32.67945196,  35.45681796],
       [ 25.84394566,  33.96237901],
       [ 26.3443385 ,  29.08448633],
       [ 25.40334419,  29.55507672],
       [ 25.33386155,  30.76759046],
       [ 24.31635409,  31.30995895],
       [ 21.15423413,  24.59312396],
       [ 21.48360856,  27.34421953],
       [ 26.49440747,  34.57597975],
       [ 29.08506986,  35.14310582],
       [ 28.5110772 ,  41.01488171],
       [ 39.16169378,  40.75706631],
       [ 33.5986282 ,  40.70740679],
       [ 30.4949467 ,  34.46128063],
       [ 27.9682028 ,  30.58734061],
       [ 22.14775482,  28.54676218],
       [ 22.0860247 ,  26.1021346 ],
       [ 22.00064656,  25.72492158],
       [ 21.48920362,  28.67755502],
       [ 27.83746415,  32.39236826],
 

In [84]:
ope=pd.Series(ope)
hig=pd.Series(hig)
low = pd.Series(low)
close = pd.Series(close)
np.array(pd.concat([ope,hig,low,close],axis=1))

array([[30.6154745 , 34.52701643, 30.47768978, 33.57493092],
       [33.57493092, 38.74723115, 33.18376623, 37.83898576],
       [37.83898576, 37.91364962, 37.5170981 , 37.66843769],
       ...,
       [42.56942682, 43.42990104, 37.2452737 , 38.136311  ],
       [38.136311  , 38.59831751, 31.3762861 , 31.97743715],
       [31.97743715, 32.24218438, 31.75423373, 31.97743715]])

In [71]:
func={"double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "bearish_flag":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
      "bullish_flag":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
      "bullish_pennat":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "bearish_pennat":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "descending_triangle":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "ascending_triangle":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "cup_handle":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "head_shoulders":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "inv_head_shoulders":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "triple_top":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "triple_bottom":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)
      }

In [ ]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}


In [ ]:
func={"double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "bearish_flag":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "bullish_flag":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "bullish_pennat":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "bearish_pennat":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "descending_triangle":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "ascending_triangle":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "cup_handle":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "head_shoulders":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "inv_head_shoulders":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "triple_top":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "triple_bottom":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "norm_params":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }

In [ ]:
#25 % for testing
#25% of no pattern for testing
#75%  -1,-1,0
#synthetic
#40% of the pattern
#40% without the pattern

In [184]:
np.random.randint(0,10)

5

In [191]:
def gen_x_y(l=round(0.4*50),pattern=["rising_wedge","falling_wedge","double_top","double_bottom"]):
    X=[]
    y=[]
    pat={"rising_wedge":1,
            "falling_wedge":2,
            "double_top":3,
            "double_bottom":4
        }
    for i in range(l):
        
        func={"rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            }
    
        date, ope, hig, low, close, start, end = func[pattern]
        ope=np.array(ope)
        hig=np.array(hig)
        low = np.array(low)
        close = np.array(close)
        X.append(np.column_stack((ope, hig, low, close)))
        y.append((start, end, pat[pattern]))
    
    for i in range(l):
        if pattern == "rising_wedge":
            m= np.random.randint(0,10)
            m = str(m)
            func={"0":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "1":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "2":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "3":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "4":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "5":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "6":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "7":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "8":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }
            date, ope, hig, low, close, start, end = func[m]
            ope=np.array(ope)
            hig=np.array(hig)
            low = np.array(low)
            close = np.array(close)
            X.append(np.column_stack((ope, hig, low, close)))
            y.append((-1, -1, 0))
        
        if pattern == "falling_wedge":
            m= np.random.randint(0,10)
            m = str(m)
            func={"0":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "1":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "2":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "3":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "4":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "5":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "6":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "7":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "8":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }
            date, ope, hig, low, close, start, end = func[m]
            ope=np.array(ope)
            hig=np.array(hig)
            low = np.array(low)
            close = np.array(close)
            X.append(np.column_stack((ope, hig, low, close)))
            y.append((-1, -1, 0))
        
        if pattern == "double_top":
            m= np.random.randint(0,10)
            m = str(m)
            func={"0":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "1":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "2":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "3":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "4":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "5":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "6":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "7":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "8":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }
            date, ope, hig, low, close, start, end = func[m]
            ope=np.array(ope)
            hig=np.array(hig)
            low = np.array(low)
            close = np.array(close)
            X.append(np.column_stack((ope, hig, low, close)))
            y.append((-1, -1, 0))
        
        if pattern == "double_bottom":
            m= np.random.randint(0,10)
            m = str(m)
            func={"0":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "1":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "2":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "3":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "4":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "5":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "6":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "7":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "8":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }
            date, ope, hig, low, close, start, end = func[m]
            ope=np.array(ope)
            hig=np.array(hig)
            low = np.array(low)
            close = np.array(close)
            X.append(np.column_stack((ope, hig, low, close)))
            y.append((-1, -1, 0))
            
    return X, y
    

In [ ]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}


In [192]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}
gen_x_y(l=round(amount["rising_wedge"]*0.4), pattern="rising_wedge")

([array([[ 16.46024145,  17.35236774,  10.82085342,  11.19339096],
         [ 11.19339096,  11.2991327 ,   9.34326493,   9.39048244],
         [  9.39048244,   9.91653322,   4.44392207,   5.38117463],
         ...,
         [177.64193258, 177.73101731, 175.92592937, 176.24138303],
         [176.24138303, 179.90221979, 175.75901546, 179.59851758],
         [179.59851758, 180.35343411, 178.75456905, 179.59851758]]),
  array([[ 37.67866245,  46.21091396,  37.10918621,  45.57519991],
         [ 45.57519991,  46.29242781,  37.15667294,  38.14940528],
         [ 38.14940528,  38.98642493,  35.82605411,  36.06748428],
         ...,
         [138.52853343, 144.81816863, 138.16968583, 144.52178454],
         [144.52178454, 147.63947758, 143.77194781, 147.18349253],
         [147.18349253, 148.09163381, 147.0629552 , 147.18349253]]),
  array([[ 67.67802774,  71.83794559,  67.32418809,  71.07439031],
         [ 71.07439031,  71.90846932,  70.90259444,  71.35553481],
         [ 71.35553481,  73.35

In [188]:
def get_X_y():
    amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}
    X_ris_wedg, y_ris_wedg = gen_x_y(l=round(amount["rising_wedge"]*0.4), pattern="rising_wedge")
    X_fal_wedg, y_fal_wedg = gen_x_y(l=round(amount["falling_wedge"]*0.4), pattern="falling_wedge")
    X_d_top, y_d_top = gen_x_y(l=round(amount["double_top"]*0.4), pattern="double_top")
    X_d_bottom, y_d_bottom = gen_x_y(l=round(amount["double_bottom"]*0.4), pattern="double_bottom")
    return X_ris_wedg, y_ris_wedg, X_fal_wedg, y_fal_wedg, X_d_top, y_d_top, X_d_bottom, y_d_bottom

In [193]:
get_X_y()

([array([[ 33.48758428,  33.76075346,  31.18063142,  31.80395308],
         [ 31.80395308,  32.36512093,  30.97858445,  32.20611551],
         [ 32.20611551,  38.58845274,  32.04914904,  37.97759687],
         ...,
         [133.05249995, 137.00796406, 132.91074096, 136.99002081],
         [136.99002081, 140.60001677, 136.60342306, 140.06201174],
         [140.06201174, 140.40021476, 139.87912246, 140.06201174]]),
  array([[ 47.70718372,  47.75030271,  46.37547266,  47.32875305],
         [ 47.32875305,  48.26380662,  46.61029553,  47.49773785],
         [ 47.49773785,  50.8790604 ,  47.21228218,  50.84942823],
         ...,
         [135.45927715, 138.27645314, 135.20000497, 137.66338411],
         [137.66338411, 138.40424185, 135.21806335, 135.44107983],
         [135.44107983, 135.48615513, 135.15032018, 135.44107983]]),
  array([[ 59.46484456,  69.62189129,  58.60940412,  69.431054  ],
         [ 69.431054  ,  76.25531194,  68.81400683,  75.43135479],
         [ 75.43135479,  76.04