In [41]:
from graph_generator import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [73]:
date, ope, hig, low, close, start, end=triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)


In [96]:
low

0      30.477690
1      33.183766
2      37.517098
3      37.626544
4      38.052748
         ...    
493    30.203382
494    30.399794
495    37.245274
496    31.376286
497    31.754234
Length: 498, dtype: float64

In [98]:
ope=np.array(low)
hig=np.array(hig)

np.column_stack((ope, hig))

array([[ 30.47768978,  34.52701643],
       [ 33.18376623,  38.74723115],
       [ 37.5170981 ,  37.91364962],
       [ 37.62654357,  39.09129713],
       [ 38.05274786,  38.91448931],
       [ 35.65880228,  39.11408373],
       [ 35.09742452,  36.58682081],
       [ 32.67945196,  35.45681796],
       [ 25.84394566,  33.96237901],
       [ 26.3443385 ,  29.08448633],
       [ 25.40334419,  29.55507672],
       [ 25.33386155,  30.76759046],
       [ 24.31635409,  31.30995895],
       [ 21.15423413,  24.59312396],
       [ 21.48360856,  27.34421953],
       [ 26.49440747,  34.57597975],
       [ 29.08506986,  35.14310582],
       [ 28.5110772 ,  41.01488171],
       [ 39.16169378,  40.75706631],
       [ 33.5986282 ,  40.70740679],
       [ 30.4949467 ,  34.46128063],
       [ 27.9682028 ,  30.58734061],
       [ 22.14775482,  28.54676218],
       [ 22.0860247 ,  26.1021346 ],
       [ 22.00064656,  25.72492158],
       [ 21.48920362,  28.67755502],
       [ 27.83746415,  32.39236826],
 

In [84]:
ope=pd.Series(ope)
hig=pd.Series(hig)
low = pd.Series(low)
close = pd.Series(close)
np.array(pd.concat([ope,hig,low,close],axis=1))

array([[30.6154745 , 34.52701643, 30.47768978, 33.57493092],
       [33.57493092, 38.74723115, 33.18376623, 37.83898576],
       [37.83898576, 37.91364962, 37.5170981 , 37.66843769],
       ...,
       [42.56942682, 43.42990104, 37.2452737 , 38.136311  ],
       [38.136311  , 38.59831751, 31.3762861 , 31.97743715],
       [31.97743715, 32.24218438, 31.75423373, 31.97743715]])

In [71]:
func={"double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "bearish_flag":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
      "bullish_flag":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
      "bullish_pennat":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "bearish_pennat":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "descending_triangle":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "ascending_triangle":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "cup_handle":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "head_shoulders":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "inv_head_shoulders":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "triple_top":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
      "triple_bottom":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)
      }

In [ ]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}


In [ ]:
func={"double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "bearish_flag":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "bullish_flag":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "bullish_pennat":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "bearish_pennat":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "descending_triangle":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "ascending_triangle":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "cup_handle":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "head_shoulders":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "inv_head_shoulders":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "triple_top":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "triple_bottom":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "norm_params":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
            }

In [ ]:
#25 % for testing
#25% of no pattern for testing
#75%  -1,-1,0
#synthetic
#40% of the pattern
#40% without the pattern

In [184]:
np.random.randint(0,10)

5

In [199]:
def gen_x_y(l=round(0.4*50),pattern=["rising_wedge","falling_wedge","double_top","double_bottom"], noise=True, general=False):
    X=[]
    y=[]
    pat={"rising_wedge":1,
            "falling_wedge":2,
            "double_top":3,
            "double_bottom":4
        }
    for i in range(l):
        
        func={"rising_wedge":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "falling_wedge":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_top":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "double_bottom":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            }
    
        date, ope, hig, low, close, start, end = func[pattern]
        ope=np.array(ope)
        hig=np.array(hig)
        low = np.array(low)
        close = np.array(close)
        X.append(np.column_stack((ope, hig, low, close)))
        y.append((start, end, pat[pattern]))
    
    if noise:
        
        for i in range(l):
            if pattern == "rising_wedge":
                m= np.random.randint(0,10)
                m = str(m)
                func={"0":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "1":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "2":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "3":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "4":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "5":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "6":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "7":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "8":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
                }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((-1, -1, 0))
        
            if pattern == "falling_wedge":
                m= np.random.randint(0,10)
                m = str(m)
                func={"0":double_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "1":double_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "2":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "3":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "4":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "5":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "6":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "7":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "8":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
                }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((-1, -1, 0))
        
            if pattern == "double_top":
                m= np.random.randint(0,10)
                m = str(m)
                func={"0":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "1":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "2":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "3":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "4":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "5":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "6":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "7":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "8":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
                }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((-1, -1, 0))
        
            if pattern == "double_bottom":
                m= np.random.randint(0,10)
                m = str(m)
                func={"0":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "1":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
                "2":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "3":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "4":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "5":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "6":cup_handle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "7":falling_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "8":rising_wedge(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
                "9":norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
                }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((-1, -1, 0))
    
    if general:
        for i in range(l):
            if pattern == "rising_wedge":
                m= np.random.randint(0,3)
                m = str(m)
                func={"0":bullish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "1":bullish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "2":ascending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((start, end, pat[pattern]))
                
            if pattern == "falling_wedge":
                m= np.random.randint(0,10)
                m = str(m)
                func={"0":bearish_flag(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2=0),
            "1":bearish_pennant(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "2":descending_triangle(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)
            }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((start, end, pat[pattern]))
                
            if pattern == "double_top":
                m= np.random.randint(0,10)
                m = str(m)
                func={
            "0":head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "1":triple_top(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)
            }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((start, end, pat[pattern]))
            
            if pattern == "double_bottom":
                m= np.random.randint(0,10)
                m = str(m)
                func={
            "0":inv_head_shoulders(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0),
            "1":triple_bottom(n=500, mu=3, sigma=5, h=1, noise_level=2, ar1 = 0.95, ar2 = 0)
            }
                date, ope, hig, low, close, start, end = func[m]
                ope=np.array(ope)
                hig=np.array(hig)
                low = np.array(low)
                close = np.array(close)
                X.append(np.column_stack((ope, hig, low, close)))
                y.append((start, end, pat[pattern]))
        
        
    return X, y
    

In [203]:
def get_rand_noise(l=round(0.4*50)):
    X=[]
    y=[]
    
    for i in range(l):
    
        date, ope, hig, low, close, start, end = norm_params(ar1=0.95, ar2=0, diff=0, n=500, mu=0, sigma=1, h=2)
        ope=np.array(ope)
        hig=np.array(hig)
        low = np.array(low)
        close = np.array(close)
        X.append(np.column_stack((ope, hig, low, close)))
        y.append((-1,-1,0))
    
    return X, y

In [204]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}

X, y = gen_x_y(l=round(amount["rising_wedge"]*0.4), pattern="rising_wedge", noise=False, general=False)

In [225]:
start = np.array(y)[:,1]+len(np.array(y))*0.1
end = np.array(y)[:,1]+len(np.array(y))*0.3
pattern = np.array(y)[:,2] - y[0][2]

array([307, 257, 128, 236,  92,  67,  65, 309, 334, 338,   5,   5, 152,
       253, 158, 200, 148, 243, 139, 160, 341, 178, 309,  37,  80, 172,
       242, 226, 109,  45, 338,  97,  68, 371, 210, 258,  41, 183, 374,
        22, 301, 149,  65,  63, 362, 192, 335, 141, 263, 237, 160,  76,
       370, 100,  17, 352,  28, 128, 271,  22, 275, 332,   8, 138, 172,
        35, 372, 254, 266,  43, 216,  74, 376,  23,  70, 244, 102,  78,
       215, 200,  58, 335,  16, 255,  22, 380, 137, 287, 235, 110, 117,
       285,   4, 261, 233, 124,  34, 266, 347,  97, 151, 386, 102, 428,
       208, 231, 294, 148,  10,  84, 189,  40, 394, 174, 248, 150, 247,
       268, 269, 115, 330,  24, 306, 194, 243, 305, 293, 312, 420,  27,
       259, 266,  87, 224, 333, 393, 307,  52, 316, 402,  28, 142, 380,
       167, 283, 182,  26, 241,  29,  96, 222, 151, 126, 346, 209, 364,
       373, 138,   7, 117,  61,  59, 408, 106,   7, 256, 211, 189, 171,
       185, 136, 108, 220, 372,  88, 283, 109, 287,  29, 263, 27

In [228]:
def get_noise(X, y):
    np.array(y)[:,0]
    start = np.array(y)[:,1]+round(len(np.array(y))*0.1)
    end = np.array(y)[:,1]+round(len(np.array(y))*0.3)
    pattern = np.array(y)[:,2] - y[0][2]
    y = list(np.column_stack((start, end, pattern)))
    return X,y

    

In [229]:
get_noise(X, y)

([array([[ 77.03206819,  81.02605112,  76.32335605,  81.01444246],
         [ 81.01444246,  89.2467822 ,  80.87310734,  88.26708618],
         [ 88.26708618,  90.44072033,  87.81720683,  90.02931889],
         ...,
         [190.87492998, 195.6459052 , 190.17428749, 195.24896211],
         [195.24896211, 195.95286665, 185.05581605, 185.43199184],
         [185.43199184, 185.80192294, 184.47119028, 185.43199184]]),
  array([[ 72.64733522,  75.20885389,  72.00390782,  74.35141148],
         [ 74.35141148,  80.10182081,  73.48970234,  80.0336929 ],
         [ 80.0336929 ,  87.96370822,  79.21899763,  87.18322604],
         ...,
         [229.25292327, 234.36424017, 229.10374716, 234.01751525],
         [234.01751525, 236.49097907, 233.79393438, 235.97377896],
         [235.97377896, 236.0418724 , 235.94835735, 235.97377896]]),
  array([[ 72.97688687,  75.15314367,  72.89004764,  74.24441883],
         [ 74.24441883,  80.18982475,  73.78933769,  79.82320399],
         [ 79.82320399,  85.18

In [ ]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}


In [200]:
amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}
gen_x_y(l=round(amount["rising_wedge"]*0.4), pattern="rising_wedge", noise=False, general=True)

([array([[ 70.262495  ,  70.94325998,  65.09202799,  65.10585073],
         [ 65.10585073,  65.35411195,  64.31845996,  64.82119107],
         [ 64.82119107,  80.15633623,  64.54594927,  79.64431761],
         ...,
         [212.35019262, 213.03599171, 211.40226224, 211.90521633],
         [211.90521633, 212.83456472, 211.24859778, 211.89463978],
         [211.89463978, 212.59277476, 211.80523782, 211.89463978]]),
  array([[40.53276887, 41.26818193, 39.24408499, 39.58916749],
         [39.58916749, 40.55208135, 34.424118  , 34.98758859],
         [34.98758859, 40.05337169, 34.75536935, 39.20644461],
         ...,
         [95.5228918 , 96.26277123, 92.67560472, 93.10898991],
         [93.10898991, 93.5568755 , 92.25391514, 92.97087182],
         [92.97087182, 93.88394283, 92.65178357, 92.97087182]]),
  array([[ 30.47679227,  31.18575596,  26.51453211,  27.18353372],
         [ 27.18353372,  27.51626025,  24.40041406,  24.96974834],
         [ 24.96974834,  28.80492686,  24.60418364,  2

In [188]:
def get_X_y(noise=True, general=False):
    amount={"rising_wedge":556,
        "falling_wedge":268,
        "double_top": 393,
        "double_bottom": 348}
    X_ris_wedg, y_ris_wedg = gen_x_y(l=round(amount["rising_wedge"]*0.4), pattern="rising_wedge", noise=noise, general=general)
    X_fal_wedg, y_fal_wedg = gen_x_y(l=round(amount["falling_wedge"]*0.4), pattern="falling_wedge", noise=noise, general=general)
    X_d_top, y_d_top = gen_x_y(l=round(amount["double_top"]*0.4), pattern="double_top", noise=noise, general=general)
    X_d_bottom, y_d_bottom = gen_x_y(l=round(amount["double_bottom"]*0.4), pattern="double_bottom", noise=noise, general=general)
    return X_ris_wedg, y_ris_wedg, X_fal_wedg, y_fal_wedg, X_d_top, y_d_top, X_d_bottom, y_d_bottom


In [193]:
get_X_y()

([array([[ 33.48758428,  33.76075346,  31.18063142,  31.80395308],
         [ 31.80395308,  32.36512093,  30.97858445,  32.20611551],
         [ 32.20611551,  38.58845274,  32.04914904,  37.97759687],
         ...,
         [133.05249995, 137.00796406, 132.91074096, 136.99002081],
         [136.99002081, 140.60001677, 136.60342306, 140.06201174],
         [140.06201174, 140.40021476, 139.87912246, 140.06201174]]),
  array([[ 47.70718372,  47.75030271,  46.37547266,  47.32875305],
         [ 47.32875305,  48.26380662,  46.61029553,  47.49773785],
         [ 47.49773785,  50.8790604 ,  47.21228218,  50.84942823],
         ...,
         [135.45927715, 138.27645314, 135.20000497, 137.66338411],
         [137.66338411, 138.40424185, 135.21806335, 135.44107983],
         [135.44107983, 135.48615513, 135.15032018, 135.44107983]]),
  array([[ 59.46484456,  69.62189129,  58.60940412,  69.431054  ],
         [ 69.431054  ,  76.25531194,  68.81400683,  75.43135479],
         [ 75.43135479,  76.04